name: Write Release Notes
description: >-
  Uses an AI agent to accumulate release notes from merged PRs into a
  release notes file.

inputs:
  output-file:
    description: Path to the release notes file (read and written by the agent)
    required: false
    default: release-notes/next.md
  style-guide:
    description: Path to a custom style guide file (overrides the built-in default)
    required: false
    default: ""
  additional-prompt:
    description: Extra instructions appended to the agent prompt
    required: false
    default: ""
  include-contributors:
    description: Whether to credit external contributors
    required: false
    default: "true"
  exclude-labels:
    description: Comma-separated list of PR labels to skip
    required: false
    default: skip-release,chore,internal
  team-members:
    description: >-
      Comma-separated GitHub usernames considered team members (not credited
      as external contributors)
    required: false
    default: ""
  anthropic-api-key:
    description: Anthropic API key
    required: false
    default: ""
  openai-api-key:
    description: OpenAI API key
    required: false
    default: ""
  google-api-key:
    description: Google AI API key
    required: false
    default: ""
  github-token:
    description: GitHub token for API access (defaults to github.token)
    required: false
    default: ""
  model:
    description: Model override (e.g. anthropic/claude-sonnet-4-5)
    required: false
    default: ""
  cagent-version:
    description: cagent version to use
    required: false
    default: v1.23.4
  add-prompt-files:
    description: Comma-separated list of additional prompt files
    required: false
    default: ""

outputs:
  exit-code:
    description: cagent exit code
    value: ${{ steps.run-agent.outputs.exit-code }}
  output-file:
    description: Path to the updated release notes file
    value: ${{ inputs.output-file }}

runs:
  using: composite
  steps:
    - name: Resolve GitHub token
      id: resolve-token
      shell: bash
      run: |
        if [[ -n "${{ inputs.github-token }}" ]]; then
          echo "token=${{ inputs.github-token }}" >> "$GITHUB_OUTPUT"
        else
          echo "token=${{ github.token }}" >> "$GITHUB_OUTPUT"
        fi

    - name: Resolve style guide
      id: resolve-style-guide
      shell: bash
      env:
        CUSTOM_STYLE_GUIDE: ${{ inputs.style-guide }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        if [[ -n "$CUSTOM_STYLE_GUIDE" && -f "$CUSTOM_STYLE_GUIDE" ]]; then
          STYLE_GUIDE="$CUSTOM_STYLE_GUIDE"
        else
          STYLE_GUIDE="${ACTION_PATH}/prompts/style-guide.md"
        fi

        FILES="${STYLE_GUIDE}"
        if [[ -n "${{ inputs.add-prompt-files }}" ]]; then
          FILES="${FILES},${{ inputs.add-prompt-files }}"
        fi
        echo "prompt-files=${FILES}" >> "$GITHUB_OUTPUT"

    - name: Run cagent
      id: run-agent
      uses: docker/cagent-action@latest
      with:
        agent: ${{ github.action_path }}/agents/release-notes.yaml
        prompt: |
          Update the release notes file at `${{ inputs.output-file }}`.

          Repository: ${{ github.server_url }}/${{ github.repository }}
          Include contributors: ${{ inputs.include-contributors }}
          Team members: ${{ inputs.team-members }}
          Exclude labels: ${{ inputs.exclude-labels }}

          ${{ inputs.additional-prompt }}
        add-prompt-files: ${{ steps.resolve-style-guide.outputs.prompt-files }}
        anthropic-api-key: ${{ inputs.anthropic-api-key }}
        openai-api-key: ${{ inputs.openai-api-key }}
        google-api-key: ${{ inputs.google-api-key }}
        github-token: ${{ steps.resolve-token.outputs.token }}
        model: ${{ inputs.model }}
        cagent-version: ${{ inputs.cagent-version }}
        yolo: true
